### ISSUE TITLE
Output the endpoint

### ISSUE THREAD

**Issue by kaihendry** [WojciechMatuszewski/APIGW-websockets#1]
Had to dig to find 😅

![image](https://user-images.githubusercontent.com/765871/85086403-14b5d000-b20d-11ea-8f47-5048e54af276.png)

Now I'm wondering how to use this:

```
[hendry@t480s APIGW-websockets]$ wscat -c  wss://ca6bnlroql.execute-api.ap-southeast-1.amazonaws.com/dev/
Connected (press CTRL+C to quit)
> hello
< {"message": "Forbidden", "connectionId":"OWeWpfkISQ0CFNg=", "requestId":"OWeXKHpAyQ0FQow="}
```

Not sure how to invoke https://github.com/WojciechMatuszewski/APIGW-websockets/blob/master/functions/send-message/send-message.go

Any clues?

**Comment by WojciechMatuszewski** [comment]
Hi there, thanks for reaching out. 

When using websockets with API gateway there is a notion `Route Selection Expression.

![image](https://user-images.githubusercontent.com/26322927/85095772-ab28c800-b1f2-11ea-8d65-8d8ba1e82325.png)

This is how API Gateway knows which lambda to call when the message is received. This makes it so that you have to send a message which has specific structure. 

The structure is:
```
{"action":"sendmessage", "data":"PAYLOAD_DATA"}
```

Please keep in mind that this repo is just an example, and the reply is static "message!" (can easily be changed though).

There is also an official AWS repo which is basically the same example (but they are using `scan` to get the connections)

https://github.com/aws-samples/simple-websockets-chat-app

**Comment by kaihendry** [comment]
Cool, I'm learning https://s.natalian.org/2020-06-19/1592551418_2560x1440.png

Guess the next thing is some vanilla JS to connect to do this from a static Web site.

I'm with your on the dynamodb non-scan. Haha


Guess the next big question is authentication. Don't want people DDOS my endpoint ideally. Can it be set max 10 ppl or something I wonder?

**Comment by WojciechMatuszewski** [comment]
You can generate API keys from the api-gateway console. This should do the trick. I have not played with them myself, but I definitely plan to do so.
